[workspace]
members = [
  "programs/sol_predict_arena"
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
sol_predict_arena = "SoLPredictArena111111111111111111111111111111"

[scripts]
test = "anchor test"
